"""add new column image in models

Revision ID: 91015f2f8fab
Revises: d3a3c28c4ac4
Create Date: 2025-12-04 14:45:45.275536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91015f2f8fab'
down_revision: Union[str, Sequence[str], None] = 'd3a3c28c4ac4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'image_url')
    # ### end Alembic commands ###
